export const PREFIX = {
  API_CALLING: '[api_calling]',
  API_CALLED_SUCCESS: '[api_called_success]',
  API_CALLED_FAILURE: '[api_called_failure]',

  NOTIFICATION: '[notification]',
  AUTH: '[auth]',
  APP_LAYOUT: '[app_layout]',
  STUDENT: '[employee]',
  SUBJECT: '[room]',
  EXAM: '[exam]',
};


export const TYPE = {
  // AppLayout
  SET_PAGE: 'SET_PAGE',
  PUSH_NOTIFICATION: 'PUSH_NOTIFICATION',
  POP_NOTIFICATION: 'POP_NOTIFICATION',

  // Auth
  LOG_IN: 'LOG_IN',
  LOG_IN_TOKEN: 'LOG_IN_TOKEN',
  LOG_OUT: 'LOG_OUT',
  SAVE_FORWARD_LOCATION: 'SAVE_FORWARD_LOCATION',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',

  // Exam
  GETTING_EXAMS: 'GETTING_EXAMS',
  GET_EXAMS_SUCCESS: 'GET_EXAMS_SUCCESS',
  GET_EXAMS_FAILURE: 'GET_EXAMS_FAILURE',

  SELECTING_EXAM: 'SELECTING_EXAM',
  SELECT_EXAM_SUCCESS: 'SELECT_EXAM_SUCCESS',
  SELECT_EXAM_FAILURE: 'SELECT_EXAM_FAILURE',

  INSERTING_EXAM: 'INSERTING_EXAM',
  INSERT_EXAM_SUCCESS: 'INSERT_EXAM_SUCCESS',
  INSERT_EXAM_FAILURE: 'INSERT_EXAM_FAILURE',

  UPDATING_EXAM: 'UPDATING_EXAM',
  UPDATE_EXAM_SUCCESS: 'UPDATE_EXAM_SUCCESS',
  UPDATE_EXAM_FAILURE: 'UPDATE_EXAM_FAILURE',

  DELETING_EXAM: 'DELETING_EXAM',
  DELETE_EXAM_SUCCESS: 'DELETE_EXAM_SUCCESS',
  DELETE_EXAM_FAILURE: 'DELETE_EXAM_FAILURE',

  // Exam_Shift
  GETTING_EXAM_SHIFTS: 'GETTING_EXAM_SHIFTS',
  GET_EXAM_SHIFTS_SUCCESS: 'GET_EXAM_SHIFTS_SUCCESS',
  GET_EXAM_SHIFTS_FAILURE: 'GET_EXAM_SHIFTS_FAILURE',

  INSERTING_EXAM_SHIFT: 'INSERTING_EXAM_SHIFT',
  INSERT_EXAM_SHIFT_SUCCESS: 'INSERT_EXAM_SHIFT_SUCCESS',
  INSERT_EXAM_SHIFT_FAILURE: 'INSERT_EXAM_SHIFT_FAILURE',

  UPDATING_EXAM_SHIFT: 'UPDATING_EXAM_SHIFT',
  UPDATE_EXAM_SHIFT_SUCCESS: 'UPDATE_EXAM_SHIFT_SUCCESS',
  UPDATE_EXAM_SHIFT_FAILURE: 'UPDATE_EXAM_SHIFT_FAILURE',

  DELETING_EXAM_SHIFT: 'DELETING_EXAM_SHIFT',
  DELETE_EXAM_SHIFT_SUCCESS: 'DELETE_EXAM_SHIFT_SUCCESS',
  DELETE_EXAM_SHIFT_FAILURE: 'DELETE_EXAM_SHIFT_FAILURE',

  // Exam_Room
  GETTING_EXAM_ROOMS: 'GETTING_EXAM_ROOMS',
  GET_EXAM_ROOMS_SUCCESS: 'GET_EXAM_ROOMS_SUCCESS',
  GET_EXAM_ROOMS_FAILURE: 'GET_EXAM_ROOMS_FAILURE',

  INSERTING_EXAM_ROOM: 'INSERTING_EXAM_ROOM',
  INSERT_EXAM_ROOM_SUCCESS: 'INSERT_EXAM_ROOM_SUCCESS',
  INSERT_EXAM_ROOM_FAILURE: 'INSERT_EXAM_ROOM_FAILURE',

  UPDATING_EXAM_ROOM: 'UPDATING_EXAM_ROOM',
  UPDATE_EXAM_ROOM_SUCCESS: 'UPDATE_EXAM_ROOM_SUCCESS',
  UPDATE_EXAM_ROOM_FAILURE: 'UPDATE_EXAM_ROOM_FAILURE',

  DELETING_EXAM_ROOM: 'DELETING_EXAM_ROOM',
  DELETE_EXAM_ROOM_SUCCESS: 'DELETE_EXAM_ROOM_SUCCESS',
  DELETE_EXAM_ROOM_FAILURE: 'DELETE_EXAM_ROOM_FAILURE',
  // Student
  GETTING_STUDENTS: 'GETTING_STUDENTS',
  GET_STUDENTS_SUCCESS: 'GET_STUDENTS_SUCCESS',
  GET_STUDENTS_FAILURE: 'GET_STUDENTS_FAILURE',

  GETTING_STUDENT: 'GETTING_STUDENT',
  GET_STUDENT_SUCCESS: 'GET_STUDENT_SUCCESS',
  GET_STUDENT_FAILURE: 'GET_STUDENT_FAILURE',

  INSERTING_STUDENT: 'INSERTING_STUDENT',
  INSERT_STUDENT_SUCCESS: 'INSERT_STUDENT_SUCCESS',
  INSERT_STUDENT_FAILURE: 'INSERT_STUDENT_FAILURE',

  UPDATING_STUDENT: 'UPDATING_STUDENT',
  UPDATE_STUDENT_SUCCESS: 'UPDATE_STUDENT_SUCCESS',
  UPDATE_STUDENT_FAILURE: 'UPDATE_STUDENT_FAILURE',

  DELETING_STUDENT: 'DELETING_STUDENT',
  DELETE_STUDENT_SUCCESS: 'DELETE_STUDENT_SUCCESS',
  DELETE_STUDENT_FAILURE: 'DELETE_STUDENT_FAILURE',

  // Subject
  GETTING_SUBJECTS: 'GETTING_SUBJECTS',
  GET_SUBJECTS_SUCCESS: 'GET_SUBJECTS_SUCCESS',
  GET_SUBJECTS_FAILURE: 'GET_SUBJECTS_FAILURE',

  GETTING_SUBJECT: 'GETTING_SUBJECT',
  GET_SUBJECT_SUCCESS: 'GET_SUBJECT_SUCCESS',
  GET_SUBJECT_FAILURE: 'GET_SUBJECT_FAILURE',

  INSERTING_SUBJECT: 'INSERTING_SUBJECT',
  INSERT_SUBJECT_SUCCESS: 'INSERT_SUBJECT_SUCCESS',
  INSERT_SUBJECT_FAILURE: 'INSERT_SUBJECT_FAILURE',

  UPDATING_SUBJECT: 'UPDATING_SUBJECT',
  UPDATE_SUBJECT_SUCCESS: 'UPDATE_SUBJECT_SUCCESS',
  UPDATE_SUBJECT_FAILURE: 'UPDATE_SUBJECT_FAILURE',

  DELETING_SUBJECT: 'DELETING_SUBJECT',
  DELETE_SUBJECT_SUCCESS: 'DELETE_SUBJECT_SUCCESS',
  DELETE_SUBJECT_FAILURE: 'DELETE_SUBJECT_FAILURE',

  // Schedule
  SET_DAYS: 'SET_DAYS',
  SELECT_STUDENTS_FOR_SCHEDULE: 'SELECT_STUDENTS_FOR_SCHEDULE',
  SELECT_SUBJECTS_FOR_SCHEDULE: 'SELECT_SUBJECTS_FOR_SCHEDULE',
  CHANGE_STUDENT_STATUS: 'CHANGE_STUDENT_STATUS',
  CHANGE_STUDENT_ABILITY: 'CHANGE_STUDENT_ABILITY',
  SAVE_WORK: 'SAVE_WORK',
  SET_HOLIDAY: 'SET_HOLIDAY',
};
