// Exam_Shift
GETTING_EXAM_ROOMS: 'GETTING_EXAM_ROOMS',
GET_EXAM_ROOMS_SUCCESS: 'GET_EXAM_ROOMS_SUCCESS',
GET_EXAM_ROOMS_FAILURE: 'GET_EXAM_ROOMS_FAILURE',

INSERTING_EXAM_ROOM: 'INSERTING_EXAM_ROOM',
INSERT_EXAM_ROOM_SUCCESS: 'INSERT_EXAM_ROOM_SUCCESS',
INSERT_EXAM_ROOM_FAILURE: 'INSERT_EXAM_ROOM_FAILURE',

UPDATING_EXAM_ROOM: 'UPDATING_EXAM_ROOM',
UPDATE_EXAM_ROOM_SUCCESS: 'UPDATE_EXAM_ROOM_SUCCESS',
UPDATE_EXAM_ROOM_FAILURE: 'UPDATE_EXAM_ROOM_FAILURE',

DELETING_EXAM_ROOM: 'DELETING_EXAM_ROOM',
DELETE_EXAM_ROOM_SUCCESS: 'DELETE_EXAM_ROOM_SUCCESS',
DELETE_EXAM_ROOM_FAILURE: 'DELETE_EXAM_ROOM_FAILURE',
